"""
Application constants and configuration values.
"""

# File upload settings
MAX_FILE_SIZE = 50 * 1024 * 1024  # 50MB
ALLOWED_EXTENSIONS = {'csv', 'xlsx', 'xls'}

# Reconciliation settings
RECON_MATCH_TOLERANCE = 0.01  # Amount tolerance for matching
DATE_TOLERANCE_DAYS = 1  # Date tolerance for matching

# Transaction statuses
TRANSACTION_STATUS_PENDING = 'PENDING'
TRANSACTION_STATUS_MATCHED = 'MATCHED'
TRANSACTION_STATUS_ANOMALY = 'ANOMALY'
TRANSACTION_STATUS_RESOLVED = 'RESOLVED'

# Anomaly types
ANOMALY_AMOUNT_MISMATCH = 'AMOUNT_MISMATCH'
ANOMALY_MISSING_INTERNAL = 'MISSING_INTERNAL'
ANOMALY_MISSING_MPR = 'MISSING_MPR'
ANOMALY_MISSING_BANK = 'MISSING_BANK'
ANOMALY_DUPLICATE = 'DUPLICATE'

# Channel types
CHANNEL_BBPS = 'BBPS'
CHANNEL_PG = 'Payment Gateway'
CHANNEL_WHATSAPP = 'WhatsApp'

# File formats
FILE_FORMAT_CSV = 'CSV'
FILE_FORMAT_EXCEL = 'EXCEL'

# Log categories
LOG_AUTH = 'AUTH'
LOG_UPLOAD = 'UPLOAD'
LOG_RECON = 'RECON'
LOG_ANALYTICS = 'ANALYTICS'
LOG_SYSTEM = 'SYSTEM'